CREATE TABLE user(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(30) NOT NULL
);

CREATE TABLE file(
fid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fname VARCHAR(50) NOT NULL,
username VARCHAR(20) NOT NULL,
fcontent MEDIUMBLOB
);